[phases.setup]
nixPkgs = ["nodejs_20", "corepack"]

[phases.install]
dependsOn = ["setup"]
cmds = [
  "corepack enable",
  "corepack prepare pnpm@9.15.4 --activate",
  "pnpm -v",
  "pnpm install --frozen-lockfile"
]

[phases.build]
dependsOn = ["install"]
cmds = [
  "pnpm --filter ./apps/api build"
]

[start]
cmd = "corepack enable && corepack prepare pnpm@9.15.4 --activate && pnpm --filter ./apps/api start:prod"
