-- AlterTable
ALTER TABLE "ExcelSheet" ADD COLUMN IF NOT EXISTS "dataRowCount" INTEGER;
ALTER TABLE "ExcelSheet" ADD COLUMN IF NOT EXISTS "headerRowsSkipped" INTEGER;
ALTER TABLE "ExcelSheet" ADD COLUMN IF NOT EXISTS "kind" TEXT;
ALTER TABLE "ExcelSheet" ADD COLUMN IF NOT EXISTS "kindReason" TEXT;
